version: '3.0'

services:

  web:
    image: nginx:latest
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
      - ${APP_NGINX_CONF}:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
      args:
        app_php_version: ${APP_PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    volumes:
      - ${APP_CODE_PATH}:/var/www/html

  mysql:
    build:
      context: ./mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ${MYSQL_DATA_VOLUME}:/var/lib/mysql
